<MyLayout>
    BoxLayout:
        #orientation: "horizontal"
        orientation: "vertical"
        size: root.width, root.height

        spacing: 20
        padding: 50

        Button:
            text: "Hello World!"

        Button:
            text: "Goodbye World!"

        Button:
            text: "I am hungry!"
            #size_hint: (0.5, 0.5)
            size_hint: (None, None)
            width: 200
            height: 50
            pos_hint: {"center_x": 0.5}
